BurgerKing/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BurgerKing.Models
{
    public class Contact
    {
        public string name { get; set; }

        public string email { get; set; }

        public string subject { get; set; }
        
        public string message { get; set; }
    }
}

BurgerKing/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BurgerKing.Models;
using System.Configuration;
using System.Net.Mail;
using Common;
using System.Net;

namespace BurgerKing.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SendContact(FormCollection field)
        {
            try
            {
                var contact = new BurgerKing.Models.Contact()
                {
                    name = field["name"],
                    email = field["email"],
                    subject = field["subject"],
                    message = field["message"]
                };

                // Gửi mail cho khách hàng
                string content = System.IO.File.ReadAllText(Server.MapPath("~/Areas/client/template/newcontact.html"));

                content = content.Replace("{{Name}}", contact.name);
                content = content.Replace("{{Email}}", contact.email);
                content = content.Replace("{{Subject}}", contact.subject);
                content = content.Replace("{{Message}}", contact.message);
                var toEmail = ConfigurationManager.AppSettings["ToEmailAddress"].ToString();

                new MailHelper().SendMail(contact.email, "Phản hồi mới từ khách hàng của Burger King", content);
                new MailHelper().SendMail(toEmail, "Phản hồi mới từ khách hàng của Burger King", content);

                return View("Index");
            }
            catch (Exception ex)
            {
                // Log lỗi hoặc xử lý lỗi tại đây
                // Ví dụ:
                Console.WriteLine("Lỗi khi gửi email: " + ex.Message);
                // Hoặc ghi vào log
                // logger.Error("Lỗi khi gửi email", ex);

                // Có thể chuyển hướng hoặc hiển thị thông báo lỗi tùy thuộc vào yêu cầu của bạn
                return View("Error"); // Chuyển hướng đến trang lỗi
            }
        }
    }
}

BurgerKing/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BurgerKing.Models;
using System.Net;
using BurgerKing.Others;
using Newtonsoft.Json.Linq;
using System.Configuration;
using System.Net.Mail;
using Common;
using Newtonsoft.Json;
using System.Data.Entity.Validation;


namespace BurgerKing.Controllers
{
    public class ShoppingCartController : Controller
    {
        private BurgerKingDBContext dbContext = new BurgerKingDBContext();
        
        private string strCart = "Cart";
       
        private int CalculateCartItemCount()
        {
            List<Cart> ListCart = (List<Cart>)Session[strCart];
            return ListCart != null ? ListCart.Sum(c => c.Quantity) : 0;
        }

        private int IsExistingCheck(int? Id)
        {
            List<Cart> ListCart = (List<Cart>)Session[strCart];
            for (int i = 0; i < ListCart.Count; i++)
            {
                if (ListCart[i].Product.ProId == Id)
                    return i;
            }
            return -1;
        }

        // GET: ShoppingCart
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetCartItemCount()
        {
            int itemCount = CalculateCartItemCount();
            return Json(new { itemCount }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult OrderNow(int? Id)
        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (Session[strCart] == null)
            {
                List<Cart> ListCart = new List<Cart>
                {
                    new Cart(dbContext.Products.Find(Id), 1)
                };
                Session[strCart] = ListCart;    
            }
            else
            {
                List<Cart> ListCart = (List<Cart>)Session[strCart];
                int check = IsExistingCheck(Id);
                if (check == -1)
                    ListCart.Add(new Cart(dbContext.Products.Find(Id), 1));
                else
                    ListCart[check].Quantity++;

                // Cập nhật số lượng sản phẩm trong giỏ hàng
                Session[strCart] = ListCart;
            }

            return RedirectToAction("Index");
        }

        public ActionResult OrderNowQuantity(int? Id, int Quantity)
        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (Session[strCart] == null)
            {
                List<Cart> ListCart = new List<Cart>
                {
                    new Cart(dbContext.Products.Find(Id), Quantity)
                };
                Session[strCart] = ListCart;
            }
            else
            {
                List<Cart> ListCart = (List<Cart>) Session[strCart];
                int check = IsExistingCheck(Id);
                if (check == -1)
                    ListCart.Add(new Cart(dbContext.Products.Find(Id), Quantity));
                else
                    ListCart[check].Quantity += Quantity;

                // Cập nhật số lượng sản phẩm trong giỏ hàng
                Session[strCart] = ListCart;
            }

            return RedirectToAction("Index");
        }

        public ActionResult RemoveItem(int? Id)
        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int check = IsExistingCheck(Id);
            List<Cart> ListCart = (List<Cart>)Session[strCart];
            ListCart.RemoveAt(check);
            if (ListCart.Count == 0)
            {
                Session[strCart] = null;
            }
            else
            {
                Session[strCart] = ListCart;
            }

            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult UpdateCart(FormCollection field)
        {
            string[] quantities = field.GetValues("quantity");
            List<Cart> ListCart = (List<Cart>)Session[strCart];
            for (int i = 0; i < ListCart.Count; i++)
            {
                ListCart[i].Quantity = Convert.ToInt32(quantities[i]);
            }
            Session[strCart] = ListCart;

            return RedirectToAction("Index");
        }
        public ActionResult ClearCart()
        {
            Session[strCart] = null;

            return RedirectToAction("Index");
        }
        public ActionResult CheckOut()
        {
            string accountInfo = Request.Cookies["AccountInfo"]?.Value;

            if (!string.IsNullOrEmpty(accountInfo))
            {
                Account acc = JsonConvert.DeserializeObject<Account>(accountInfo);

                if (acc != null)
                {
                    ViewBag.Name = acc.Name;
                    ViewBag.Email = acc.Email;
                    ViewBag.Phone = acc.Phone;
                    ViewBag.Address = acc.Address;
                }
            }

            return View();
        }

        [HttpPost]
        public ActionResult ProcessOrder(FormCollection field)
        {
            List<Cart> ListCart = (List<Cart>)Session[strCart];

            // Tọa một Guid mới
            Guid newGuid = Guid.NewGuid();

            // Chuyển đổi Guid thành chuỗi và loại bỏ ký tự gạch nối
            string orderCode = newGuid.ToString("N");

            orderCode = orderCode.Substring(0, 10);

            //1. Lưu Hóa đơn vào bảng Order
            var order = new BurgerKing.Models.Order()
            {
                OrderId = orderCode,
                CustomerName = field["cusName"],
                CustomerPhone = field["cusPhone"],
                CustomerEmail = field["cusEmail"],
                CustomerAddress = field["cusAddress"],
                OrderDate = DateTime.Now,
                OrderNote = field["ordNote"],
                PaymentType = "",
                Status = OrderStatus.Processing
            };

            // Thêm Order mới vào context
            dbContext.Orders.Add(order);

            // Lưu thay đổi để có OrderId
            dbContext.SaveChanges();

            // Tạo và thêm OrderDetails
            foreach (Cart cart in ListCart)
            {
                OrderDetail orderDetail = new OrderDetail()
                {
                    OrderId = order.OrderId,
                    ProductId = cart.Product.ProId,
                    Quantity = Convert.ToInt32(cart.Quantity),
                    Price = Convert.ToDouble(cart.Product.ProPrice)
                };
                dbContext.OrderDetails.Add(orderDetail);
            }

            // Lưu thay đổi cho OrderDetails
            dbContext.SaveChanges();

            // Gán giá trị của OrderId
            var OrderId = order.OrderId;

            // ViewBag hiển thị OrderId
            ViewBag.OrderId = OrderId;

            // Tính tổng số tiền đơn hàng
            var TotalPrice = ListCart.Sum(n => n.Product.ProPrice * n.Quantity);

            // ViewBag hiển thị tổng số tiền của đơn hàng
            ViewBag.TotalPrice = TotalPrice;

            return View("OrderSuccess");
        }
    }
}

BurgerKing/Views/Contact/Index.cshtml
@using Newtonsoft.Json;
@using BurgerKing.Models;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    <!-- Contact Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                <h5 class="section-title ff-secondary text-center text-primary fw-normal">Liên hệ</h5>
                <h1 class="mb-5">Liên hệ với chúng tôi</h1>
            </div>
            <div class="row g-4">
                <div class="col-12">
                    <div class="row gy-4">
                        <div class="col-md-4">
                            <h5 class="section-title ff-secondary fw-normal text-start text-primary">Email</h5>
                            <p><i class="fa fa-envelope-open text-primary me-2"></i>2000002680@nttu.edu.vn</p>
                        </div>
                        <div class="col-md-4">
                            <h5 class="section-title ff-secondary fw-normal text-start text-primary">Số điện thoại</h5>
                            <p><i class="fa fa-phone-alt text-primary me-2"></i>0706 996 998</p>
                        </div>
                        <div class="col-md-4">
                            <h5 class="section-title ff-secondary fw-normal text-start text-primary">Địa chỉ</h5>
                            <p><i class="fa fa-map-marker-alt text-primary me-2"></i>Đại học Nguyễn Tất Thành</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 wow fadeIn" data-wow-delay="0.1s">
                    <iframe class="position-relative rounded w-100 h-100"
                            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3918.3652029854666!2d106.69204877421089!3d10.859802889294063!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317529c17978287d%3A0xec48f5a17b7d5741!2zVHLGsOG7nW5nIMSQ4bqhaSBo4buNYyBOZ3V54buFbiBU4bqldCBUaMOgbmggLSBDxqEgc-G7nyBxdeG6rW4gMTI!5e0!3m2!1svi!2s!4v1700563672045!5m2!1svi!2s"
                            frameborder="0" style="min-height: 350px; border:0;" allowfullscreen="" aria-hidden="false"
                            tabindex="0"></iframe>
                </div>
                <div class="col-md-6">
                    <div class="wow fadeInUp" data-wow-delay="0.2s">
                        @{
                            string accountInfo = Request.Cookies["AccountInfo"]?.Value;

                            if (!string.IsNullOrEmpty(accountInfo))
                            {
                                Account acc = JsonConvert.DeserializeObject<Account>(accountInfo);

                                if (acc != null)
                                {
                                    ViewBag.Name = acc.Name;
                                    ViewBag.Email = acc.Email;
                                }
                            }
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            using (Html.BeginForm("SendContact", "Contact", FormMethod.Post, new { enctype = "multipart/form-data" }))
                            {
                                @*@Html.AntiForegyToken()*@
                                <div class="row g-3">
                                    <div class="col-md-6">
                                        <div class="form-floating">
                                            <input type="text" class="form-control" name="name" placeholder="Your Name" required value="@ViewBag.Name">
                                            <label for="name">Họ và Tên</label>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-floating">
                                            <input type="text" class="form-control" name="email" placeholder="Your Email" required value="@ViewBag.Email">
                                            <label for="email">Email</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-floating">
                                            <input type="text" class="form-control" name="subject" placeholder="Subject">
                                            <label for="subject">Tiêu đề</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-floating">
                                            <textarea class="form-control" placeholder="Leave a message here" name="message" style="height: 150px" required></textarea>
                                            <label for="message">Nội dung</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <input type="submit" name="Process Order" class="btn btn-warning p-2" style="width:20%; color:white" />
                                    </div>
                                </div>
                            }
                        }
                        else
                        {
                            using (Html.BeginForm("SendContact", "Contact", FormMethod.Post, new { enctype = "multipart/form-data" }))
                            {
                                @*@Html.AntiForegyToken()*@
                                <div class="row g-3">
                                    <div class="col-md-6">
                                        <div class="form-floating">
                                            <input type="text" class="form-control" name="name" placeholder="Your Name" required>
                                            <label for="name">Họ và Tên</label>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-floating">
                                            <input type="text" class="form-control" name="email" placeholder="Your Email" required>
                                            <label for="email">Email</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-floating">
                                            <input type="text" class="form-control" name="subject" placeholder="Subject">
                                            <label for="subject">Tiêu đề</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-floating">
                                            <textarea class="form-control" placeholder="Leave a message here" name="message" style="height: 150px" required></textarea>
                                            <label for="message">Nội dung</label>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <input type="submit" name="Process Order" class="btn btn-warning p-2" style="width:20%; color:white" />
                                    </div>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->
}

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script> <!-- Make sure jQuery is included before this script -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<script>
    $(document).ready(function () {
        // Hàm xử lý khi form được submit
        $('form').submit(function (e) {
            e.preventDefault(); // Ngăn chặn hành động mặc định của form

            // Hiển thị SweetAlert2 loading animation
            Swal.fire({
                title: 'Phản hồi của bạn đang được gửi đi...',
                allowOutsideClick: false,
                onBeforeOpen: () => {
                    Swal.showLoading();
                },
                showConfirmButton: false,
                customClass: {
                    loader: 'custom-loader-class' // Custom class for the loader
                }
            });

            // Gọi action để xử lý phản hồi
            $.ajax({
                url: $(this).attr('action'),
                type: $(this).attr('method'),
                data: $(this).serialize(),
                success: function () {
                    // Đóng SweetAlert2 loading animation
                    Swal.close();

                    // Hiển thị thông báo thành công bằng SweetAlert2
                    Swal.fire({
                        icon: 'success',
                        title: 'Phản hồi đã được gửi thành công!',
                        showConfirmButton: false,
                        timer: 1500
                    });
                },
                error: function () {
                    // Đóng SweetAlert2 loading animation
                    Swal.close();

                    // Hiển thị thông báo lỗi nếu có lỗi xảy ra
                    Swal.fire({
                        icon: 'error',
                        title: 'Oops...',
                        text: 'Đã có lỗi xảy ra!'
                    });
                }
            });
        });
    });
</script>


@section scripts{
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script>
        $(document).ready(function () {
            // Gọi hàm cập nhật số lượng mục trong giỏ hàng khi trang được tải
            updateCartItemCount();

            // Hàm để gọi action và cập nhật số lượng trên giao diện
            function updateCartItemCount() {
                $.ajax({
                    url: '@Url.Action("GetCartItemCount", "ShoppingCart")', // Đường dẫn đến action
                    type: 'GET',
                    success: function (data) {
                        // Xử lý dữ liệu trả về, ở đây có thể làm bất cứ điều gì bạn muốn
                        console.log('Số lượng mục trong giỏ hàng: ' + data.itemCount);

                        // Cập nhật giao diện người dùng với số lượng mới
                        $('#cart_count').text(data.itemCount);
                    },
                    error: function () {
                        console.log('Lỗi khi gọi action');
                    }
                });
            }
        });
    </script>
}