BurgerKing/Areas/Admin/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BurgerKing.Models;

namespace BurgerKing.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AccountsController : Controller
    {
        private BurgerKingDBContext db = new BurgerKingDBContext();

        // GET: Admin/Accounts
        public ActionResult Index()
        {
            var accounts = db.Accounts.Include(a => a.Role);
            return View(accounts.ToList());
        }

        // GET: Admin/Accounts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            return View(account);
        }

        // GET: Admin/Accounts/Create
        public ActionResult Create()
        {
            ViewBag.RoleId = new SelectList(db.Roles, "RoleId", "RoleName");
            return View();
        }

        // POST: Admin/Accounts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Account account, HttpPostedFileBase file)
        {

            if (file != null && file.ContentLength > 0)
            {
                string filename = Path.GetFileName(file.FileName);
                string _filename = DateTime.Now.ToString("yymmssfff") + filename;
                string extension = Path.GetExtension(file.FileName);
                string path = Path.Combine(Server.MapPath("~/images/"), _filename);

                // Tên ảnh cho Image Account
                account.Image = _filename;

                if (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png")
                {
                    if (file.ContentLength <= 1000000)
                    {
                        
                        TryUpdateModel(account); 
                        if (ModelState.IsValid)
                        {
                            db.Accounts.Add(account);
                            db.SaveChanges();
                            file.SaveAs(path);
                            ViewBag.msg = "Record Added";
                            ModelState.Clear();
                            return RedirectToAction("Index");
                        }
                    }
                    else
                    {
                        ViewBag.msg = "Kích thước tệp không hợp lệ (phải nhỏ hơn hoặc bằng 1MB)";
                    }
                }
                else
                {
                    ViewBag.msg = "Định dạng tệp không hợp lệ (chỉ chấp nhận các định dạng JPG, JPEG và PNG)";
                }
            }
            else
            {
                ViewBag.msg = "Vui lòng chọn tệp";
            }

            ViewBag.RoleId = new SelectList(db.Roles, "RoleId", "RoleName", account.RoleId);
            return View(account);
        }

        // GET: Admin/Accounts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            ViewBag.RoleId = new SelectList(db.Roles, "RoleId", "RoleName", account.RoleId);
            return View(account);
        }

        // POST: Admin/Accounts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Account account, HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
            {
                string filename = Path.GetFileName(file.FileName);
                string _filename = DateTime.Now.ToString("yymmssfff") + filename;
                string extension = Path.GetExtension(file.FileName);
                string path = Path.Combine(Server.MapPath("~/images/"), _filename);

                // Tên ảnh cho Image Account
                account.Image = _filename;

                if (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png")
                {
                    if (file.ContentLength <= 1000000)
                    {

                        TryUpdateModel(account);
                        if (ModelState.IsValid)
                        {
                            db.Entry(account).State = EntityState.Modified;
                            db.SaveChanges();
                            file.SaveAs(path);
                            ViewBag.msg = "Record Added";
                            ModelState.Clear();
                            return RedirectToAction("Index");
                        }
                    }
                    else
                    {
                        ViewBag.msg = "Kích thước tệp không hợp lệ (phải nhỏ hơn hoặc bằng 1MB)";
                    }
                }
                else
                {
                    ViewBag.msg = "Định dạng tệp không hợp lệ (chỉ chấp nhận các định dạng JPG, JPEG và PNG)";
                }
            }
            else
            {
                ViewBag.msg = "Vui lòng chọn tệp";
            }

            ViewBag.RoleId = new SelectList(db.Roles, "RoleId", "RoleName", account.RoleId);
            return View(account);
        }

        // GET: Admin/Accounts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            return View(account);
        }

        // POST: Admin/Accounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Account account = db.Accounts.Find(id);
            db.Accounts.Remove(account);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BurgerKing/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Security.Cryptography;
using System.Web.Security;
using System.Text;
using BurgerKing.Models;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using Newtonsoft.Json;

namespace BurgerKing.Controllers
{
    public class AccountController : Controller
    {

        // Đăng nhập
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(FormCollection form)
        {
            using (BurgerKingDBContext dbContext = new BurgerKingDBContext())
            {
                string emailOrPhoneNumber = form["EmailOrPhone"];
                string password = form["Password"];

                if (ModelState.IsValid)
                {
                    if (IsEmail(emailOrPhoneNumber))
                    {
                        password = GetSHA256(password);
                        bool isValidAccount = dbContext.Accounts.Any(acc => acc.Email == emailOrPhoneNumber && acc.Password.ToLower() == password.ToLower());
                        if (isValidAccount)
                        {
                            // Xác thực người dùng
                            FormsAuthentication.SetAuthCookie(emailOrPhoneNumber, false);

                            // Truyền đối tượng vào Cookie thông qua Json
                            HttpCookie cookie = new HttpCookie("AccountInfo");
                            var account = new Account()
                            {
                                Id = dbContext.Accounts.Where(acc => acc.Email == emailOrPhoneNumber && acc.Password.ToLower() == password.ToLower()).Select(acc => acc.Id).FirstOrDefault(),
                                Name = dbContext.Accounts.Where(acc => acc.Email == emailOrPhoneNumber && acc.Password.ToLower() == password.ToLower()).Select(acc => acc.Name).FirstOrDefault(),
                                Email = emailOrPhoneNumber,
                                Phone = dbContext.Accounts.Where(acc => acc.Email == emailOrPhoneNumber && acc.Password.ToLower() == password.ToLower()).Select(acc => acc.Phone).FirstOrDefault(),
                                Image = dbContext.Accounts.Where(acc => acc.Email == emailOrPhoneNumber && acc.Password.ToLower() == password.ToLower()).Select(acc => acc.Image).FirstOrDefault(),
                                Address = dbContext.Accounts.Where(acc => acc.Email == emailOrPhoneNumber && acc.Password.ToLower() == password.ToLower()).Select(acc => acc.Address).FirstOrDefault()
                            };
                            string accountJson = JsonConvert.SerializeObject(account);
                            cookie.Value = accountJson;
                            Response.Cookies.Add(cookie);

                            // Kiểm tra quyền truy cập
                            int? RoleId = dbContext.Accounts.Where(acc => acc.Email == emailOrPhoneNumber && acc.Password.ToLower() == password.ToLower()).Select(acc => acc.RoleId).FirstOrDefault();
                            if (RoleId == 1)
                            {
                                return RedirectToAction("Index", "Products", new { area = "Admin" });
                            }
                            if (RoleId == 3)
                            {
                                return RedirectToAction("Index","Home");
                            }
                        }
                    }
                    else if (IsPhoneNumber(emailOrPhoneNumber))
                    {
                        password = GetSHA256(password);
                        bool isValidAccount = dbContext.Accounts.Any(acc => acc.Phone == emailOrPhoneNumber && acc.Password.ToLower() == password.ToLower());
                        if (isValidAccount)
                        {
                            // Xác thực người dùng
                            FormsAuthentication.SetAuthCookie(emailOrPhoneNumber, false);

                            // Truyền đối tượng vào Cookie thông qua Json
                            HttpCookie cookie = new HttpCookie("AccountInfo");
                            var account = new Account()
                            {
                                Id = dbContext.Accounts.Where(acc => acc.Email == emailOrPhoneNumber && acc.Password.ToLower() == password.ToLower()).Select(acc => acc.Id).FirstOrDefault(),
                                Name = dbContext.Accounts.Where(acc => acc.Phone == emailOrPhoneNumber && acc.Password.ToLower() == password.ToLower()).Select(acc => acc.Name).FirstOrDefault(),
                                Email = dbContext.Accounts.Where(acc => acc.Phone == emailOrPhoneNumber && acc.Password.ToLower() == password.ToLower()).Select(acc => acc.Email).FirstOrDefault(),
                                Phone = emailOrPhoneNumber,
                                Image = dbContext.Accounts.Where(acc => acc.Phone == emailOrPhoneNumber && acc.Password.ToLower() == password.ToLower()).Select(acc => acc.Image).FirstOrDefault(),
                                Address = dbContext.Accounts.Where(acc => acc.Phone == emailOrPhoneNumber && acc.Password.ToLower() == password.ToLower()).Select(acc => acc.Address).FirstOrDefault()
                            };
                            string accountJson = JsonConvert.SerializeObject(account);
                            cookie.Value = accountJson;
                            Response.Cookies.Add(cookie);

                            // Kiểm tra quyền truy cập
                            int? RoleId = dbContext.Accounts.Where(acc => acc.Phone == emailOrPhoneNumber && acc.Password.ToLower() == password.ToLower()).Select(acc => acc.RoleId).FirstOrDefault();
                            if (RoleId == 1)
                            {
                                return RedirectToAction("Index","Products", new { area = "Admin" });
                            }
                            if (RoleId == 3)
                            {
                                return RedirectToAction("Index","Home");
                            }
                        }
                    }
                    ModelState.AddModelError("", "Sai tên đăng nhập hoặc mật khẩu");
                    return View();
                }
            }

            return View();
        }


        // Đăng kí
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(FormCollection form)
        {
            using (BurgerKingDBContext dbContext = new BurgerKingDBContext())
            {
                string name = form["Name"];
                string email = form["Email"];
                string phone = form["Phone"];
                string password = form["Password"];
                string confirmPassword = form["ConfirmPassword"]; // Thêm dòng này để lấy mật khẩu nhập lại

                // Kiểm tra xem email đã tồn tại hay chưa
                bool isEmailExist = dbContext.Accounts.Any(acc => acc.Email == email);

                // Kiểm tra xem số điện thoại đã tồn tại hay chưa
                bool isPhoneExist = dbContext.Accounts.Any(acc => acc.Phone == phone);

                // Nếu email hoặc số điện thoại đã tồn tại, trả về thông báo lỗi
                if (isEmailExist || isPhoneExist)
                {
                    ModelState.AddModelError("", "Email hoặc số điện thoại đã tồn tại. Vui lòng nhập lại");
                    return View();
                }

                // Kiểm tra mật khẩu có độ dài trên 6 kí tự và chứa cả chữ và số
                if (password.Length < 6 || !password.Any(char.IsDigit) || !password.Any(char.IsLetter))
                {
                    ModelState.AddModelError("", "Mật khẩu phải có ít nhất 6 kí tự và bao gồm cả chữ và số.");
                    return View();
                }

                // Kiểm tra xem mật khẩu và mật khẩu nhập lại có khớp nhau hay không
                if (password != confirmPassword)
                {
                    ModelState.AddModelError("", "Mật khẩu và mật khẩu nhập lại không khớp.");
                    return View();
                }

                // Thêm tài khoản vào Cơ sở dữ liệu
                var newAccount = new Account
                {
                    Name = name,
                    Image = "male.jpg", // Hình ảnh mặc định
                    Email = email,
                    Phone = phone,
                    Address = "", // Địa chỉ mặc định là chuỗi rỗng
                    Password = GetSHA256(password),
                    // Thiết lập quyền mặc định là khách hàng
                    RoleId = dbContext.Roles.FirstOrDefault(r => r.RoleName == "Customer").RoleId
                };

                dbContext.Accounts.Add(newAccount);
                dbContext.SaveChanges();

                return RedirectToAction("Login", "Account");
            }
        }


        // Đăng xuất
        private string strCart = "Cart";
        public ActionResult Logout()
        {
            // Xóa giỏ hàng khi đăng xuất
            if (Session[strCart] != null)
            {
                Session.Remove(strCart);
            }

            // Xóa thông tin của AccountInfo
            if (Request.Cookies["AccountInfo"] != null)
            {
                var infock = new HttpCookie("AccountInfo");
                infock.Expires = DateTime.Now.AddDays(-1);
                Response.Cookies.Add(infock);
            }

            // Xóa thông tin xác thực
            FormsAuthentication.SignOut();

            return RedirectToAction("Index", "Home");
        }

        // Kiểm tra số điện thoại hợp lệ hay không
        private bool IsPhoneNumber(string input)
        {
            return !string.IsNullOrEmpty(input) && input.Length >= 10 && input.All(char.IsDigit);
        }

BurgerKing/Areas/Admin/Views/Accounts/Create.cshtml
@model BurgerKing.Models.Account

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Create", "Accounts", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title" style="font-weight:bold"> Thêm tài khoản mới </h3>
        </div>
        <div class="row">
            <div class="col-lg-5 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title" style="font-weight:bold">Ảnh đại diện</h4>
                        <img id="previewImage" src="#" alt="Preview Image" style="width: 100%; height: auto; display: none;" />
                        <br />
                        <input type="file" class="form-control file-upload-info" name="file" required="required" id="file" onchange="displayImage(this)" style="background-color: #fff; padding: 0.94rem 1.375rem; color: #212529; border: 1px solid #ebedf2; width: 100% !important;" />
                        @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-md-7 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <form class="forms-sample">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                <h4 class="card-title" style="font-weight:bold">Họ và tên</h4>
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <h4 class="card-title" style="font-weight:bold">Email</h4>
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <h4 class="card-title" style="font-weight:bold">Số điện thoại</h4>
                                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <h4 class="card-title" style="font-weight:bold">Địa chỉ</h4>
                                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <h4 class="card-title" style="font-weight:bold">Mật khẩu</h4>
                                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <h4 class="card-title" style="font-weight:bold">Phân quyền</h4>
                                @Html.DropDownList("RoleId", null, htmlAttributes: new { @class = "dropdown-toggle", style = "background-color: #fff; padding: 0.94rem 1.375rem; color: #212529; border: 1px solid #ebedf2; width: 100% !important;" })
                                @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger" })
                            </div>
                            <button type="submit" value="Create" class="btn btn-gradient-success btn-fw">Save</button>
                            <button class="btn btn-light"> @Html.ActionLink("Cancel", "Index")</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script>
    function displayImage(input) {
        var fileInput = input;
        var previewImage = document.getElementById('previewImage');

        if (fileInput.files && fileInput.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                previewImage.src = e.target.result;
                previewImage.style.display = 'block';
            };

            reader.readAsDataURL(fileInput.files[0]);
        }
    }
</script>

BurgerKing/Areas/Admin/Views/Accounts/Edit.cshtml
@model BurgerKing.Models.Account

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Edit", "Accounts", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title" style="font-weight:bold"> Chỉnh sửa thông tin tài khoản </h3>
        </div>
        <div class="row">
            <div class="col-lg-5 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title" style="font-weight:bold">Ảnh đại diện</h4>
                        <img id="previewImage" src="~/images/@Model.Image" alt="Preview Image" style="width: 100%; height: auto;" />
                        <br />
                        <input type="file" class="form-control file-upload-info" name="file" required="required" id="file" onchange="displayImage(this)" style="background-color: #fff; padding: 0.94rem 1.375rem; color: #212529; border: 1px solid #ebedf2; width: 100% !important;" />
                        @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-md-7 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <form class="forms-sample">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.Id)
                            <div class="form-group">
                                <h4 class="card-title" style="font-weight:bold">Mã tài khoản</h4>
                                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <h4 class="card-title" style="font-weight:bold">Họ và tên</h4>
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <h4 class="card-title" style="font-weight:bold">Email</h4>
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <h4 class="card-title" style="font-weight:bold">Số điện thoại</h4>
                                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <h4 class="card-title" style="font-weight:bold">Địa chỉ</h4>
                                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <h4 class="card-title" style="font-weight:bold">Mật khẩu</h4>
                                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                <h4 class="card-title" style="font-weight:bold">Phân quyền</h4>
                                @Html.DropDownList("RoleId", null, htmlAttributes: new { @class = "dropdown-toggle", style = "background-color: #fff; padding: 0.94rem 1.375rem; color: #212529; border: 1px solid #ebedf2; width: 100% !important;" })
                                @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger" })
                            </div>
                            <button type="submit" value="Save" class="btn btn-gradient-success btn-fw">Save</button>
                            <button class="btn btn-light"> @Html.ActionLink("Cancel", "Index")</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script>
    function displayImage(input) {
        var fileInput = input;
        var previewImage = document.getElementById('previewImage');

        if (fileInput.files && fileInput.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                previewImage.src = e.target.result;
                previewImage.style.display = 'block';
            };

            reader.readAsDataURL(fileInput.files[0]);
        }
    }
</script>

BurgerKing/Areas/Admin/Views/Accounts/Index.cshtml
@model IEnumerable<BurgerKing.Models.Account>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="content-wrapper">
    <div class="page-header">
        <button id="button-create" type="button" class="btn btn-gradient-primary btn-icon-text">
            <i class="mdi mdi-library-plus btn-icon-prepend"></i>Thêm tài khoản mới
        </button>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Quản lý thông tin</a></li>
                <li class="breadcrumb-item active" aria-current="page">Tài khoản</li>
            </ol>
        </nav>
    </div>
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title" style="font-weight:bold">Tài khoản</h4>
                    </p>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th style="font-weight:bold">Họ và tên</th>
                                    <th style="font-weight:bold">Email</th>
                                    <th style="font-weight:bold">Số điện thoại</th>
                                    <th style="font-weight:bold">Phân quyền</th>
                                    <th style="font-weight:bold">Sửa tài khoản</th>
                                    <th style="font-weight:bold">Chi tiết tài khoản</th>
                                    <th style="font-weight:bold">Xóa tài khoản</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem => item.Name)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Email)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Phone)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Role.RoleName)</td>
                                        <td>@Html.ActionLink("Edit", "Edit", new { id = item.Id })</td>
                                        <td>@Html.ActionLink("Details", "Details", new { id = item.Id })</td>
                                        <td>@Html.ActionLink("Delete", "Delete", new { id = item.Id })</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(document).ready(function () {
        $("#button-create").click(function () {
            window.location.href = '@Url.Action("Create", "Accounts")';
        });
    });
</script>